import React from 'react'

const Proof = () => {
    return (
        <section className="bg-black py-20">
            <div className="max-w-5xl mx-auto px-4 grid md:grid-cols-2 gap-10 items-center">

                <div>
                    <h4 className="text-2xl text-white font-medium mb-4">
                        Real Examples, Real Results
                    </h4>
                    <p className="text-neutral-400">
                        PingGenius analyzes LinkedIn profiles to understand
                        role, company, and context, then generates complete 
                        outreach sequences - from connection requests to follow-ups - 
                        that feel personal and relevant.
                    </p>
                    <p className="mt-4 text-sm text-neutral-500">
                        These are actual sequences generated by PingGenius for real profiles.
                    </p>
                </div>

                <div className="bg-neutral-900 rounded-xl p-6 text-left text-sm text-neutral-300 leading-relaxed">
                    <strong>Profile:</strong> AI Systems Engineer & Founder @TDBase<br /><br />
                    
                    Connection Note:<br />
                    "Your insights as an AI Systems Engineer caught my eye. Would be great to connect with others navigating AI tool switching."<br /><br />
                    
                    DM:<br />
                    "Loved your point about switching between ChatGPT and Gemini. How do you usually handle keeping context consistent across different AI tools without losing flow?"<br /><br />
                    
                    Follow-up:<br />
                    "Just circling back on my previous message. Was curious if you've found any clever ways to simplify those AI tool context switches when you're busy."
                </div>
            </div>
        </section>

    )
}

export default Proof